# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2686e7fcb4a4bc058aa03ca01074f24b2efcf7fd61a94f5d70d4ecca6e883bcc96248baf023f082de2a5f0a2e4c350ced41991716f61a4ac0bc2b2b8d8366344

test:
  secret_key_base: a52a0502b5b3c227a0e792cfe59bc0a83a745007a6d20d2cf0eb2494ef17fd0aa320cffc7bbf5168505229dee5e850868629cfa7a2901cc0e3c5ad4110d5adfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
